### ISSUE TITLE
Develop a reading list of related materials

### ISSUE THREAD

**Issue by dhs-aws** [dhs-aws/death-and-the-digital-estate#2]
Develop a reading list of related work, documents, or other sources which can be used to inform the participants of the community group.

**Comment by xmlgrrl** [comment]
Here are some suggestions:

https://sovrin.org/a-deeper-understanding-of-implementing-guardianship/ (and items linked therein)
https://trustandwill.com/learn/what-is-rufadaa
https://kantara.atlassian.net/wiki/spaces/uma/pages/4849814/UMA+legal+subgroup+notes (and items linked therein)
https://datatracker.ietf.org/doc/html/rfc8693 (for on-behalf-of semantics)

**Comment by dhs-aws** [comment]
Thanks @xmlgrrl, I've added them to https://github.com/dhs-aws/death-and-the-digital-estate/blob/main/resources.md.

**Comment by dhs-aws** [comment]
Closing this issue - please create PRs on https://github.com/dhs-aws/death-and-the-digital-estate/blob/main/resources.md moving forward.
